on: [push, pull_request]
name: CI
jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
    # PREPARE
    - name: Install Go 1.16
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: go mod download

    # TESTS
    - name: Run tests
      run: go test -v -race -covermode atomic -coverprofile=covprofile ./...

    # TEST COVERAGE
    - name: Install goveralls
      env:
        GO111MODULE: off
      run: go get github.com/mattn/goveralls

    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=covprofile -service=github

    # LINT
    - name: Install golint
      run: go get golang.org/x/lint/golint

    - name: Install golangci-lint
      run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.41.1

    - name: go vet
      continue-on-error: true
      run: go vet ./...

    - name: golangci-lint
      continue-on-error: true
      run: golangci-lint run ./...

    - name: golint
      continue-on-error: true
      run: golint -set_exit_status $(go list ./...)
